### PR TITLE
More information, why syncloud is better.

### PR DESCRIPTION
**Pull request by klmhsb42**
-Some ideas to show more information, why syncloud is better.
-Add other companies to show of each idea/type at least one.
-"Librem one files" is not avaible yet, but could be compared in future

(Spanish translation was already merged in earlier pull request...)

### CODE REVIEW

**Comment by cyberb** [comment]
Could you rebase this branch?

**Comment by cyberb** [comment]
@klmhsb42 could you rebase and squash this?

**Comment by klmhsb42** [comment]
see #41

**Comment by klmhsb42** [comment]
see #42 sorry

**Pull request closed without merging**
